[0m22:34:14.218700 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1070b3d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1182a4d60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1182a5420>]}


============================== 22:34:14.220873 | 32253ba0-f77e-47cf-a500-2f1dd50f01fd ==============================
[0m22:34:14.220873 [info ] [MainThread]: Running with dbt=1.9.0
[0m22:34:14.221144 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/Users/lorenagongang/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m22:34:14.227986 [info ] [MainThread]: dbt version: 1.9.0
[0m22:34:14.228172 [info ] [MainThread]: python version: 3.10.11
[0m22:34:14.228302 [info ] [MainThread]: python path: /Users/lorenagongang/Documents/projects/datawarehouse_project/env/bin/python3
[0m22:34:14.228427 [info ] [MainThread]: os info: macOS-15.1.1-arm64-arm-64bit
[0m22:34:14.289748 [debug] [MainThread]: Redshift adapter: Setting redshift_connector to ERROR
[0m22:34:14.289995 [debug] [MainThread]: Redshift adapter: Setting redshift_connector.core to ERROR
[0m22:34:14.327259 [info ] [MainThread]: Using profiles dir at /Users/lorenagongang/.dbt
[0m22:34:14.327516 [info ] [MainThread]: Using profiles.yml file at /Users/lorenagongang/.dbt/profiles.yml
[0m22:34:14.327656 [info ] [MainThread]: Using dbt_project.yml file at /Users/lorenagongang/Documents/projects/datawarehouse_project/Infra/dbt_project.yml
[0m22:34:14.328055 [info ] [MainThread]: adapter type: redshift
[0m22:34:14.328210 [info ] [MainThread]: adapter version: 1.9.0
[0m22:34:14.328342 [info ] [MainThread]: Configuration:
[0m22:34:14.328462 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m22:34:14.328586 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m22:34:14.328701 [info ] [MainThread]: Required dependencies:
[0m22:34:14.328839 [debug] [MainThread]: Executing "git --help"
[0m22:34:14.339727 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m22:34:14.340202 [debug] [MainThread]: STDERR: "b''"
[0m22:34:14.340354 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m22:34:14.340508 [info ] [MainThread]: Connection:
[0m22:34:14.340713 [info ] [MainThread]:   host: my-healthcare-redshift-cluster.cmzewdchmvkc.eu-west-3.redshift.amazonaws.com
[0m22:34:14.340844 [info ] [MainThread]:   user: exampleuser
[0m22:34:14.340958 [info ] [MainThread]:   port: 5439
[0m22:34:14.341072 [info ] [MainThread]:   database: my_healthcare_datawarehouse
[0m22:34:14.341195 [info ] [MainThread]:   method: database
[0m22:34:14.341306 [info ] [MainThread]:   cluster_id: None
[0m22:34:14.341418 [info ] [MainThread]:   iam_profile: None
[0m22:34:14.341527 [info ] [MainThread]:   schema: public
[0m22:34:14.341639 [info ] [MainThread]:   sslmode: prefer
[0m22:34:14.341749 [info ] [MainThread]:   region: None
[0m22:34:14.341872 [info ] [MainThread]:   sslmode: prefer
[0m22:34:14.342045 [info ] [MainThread]:   region: None
[0m22:34:14.342180 [info ] [MainThread]:   autocreate: False
[0m22:34:14.342298 [info ] [MainThread]:   db_groups: []
[0m22:34:14.342409 [info ] [MainThread]:   ra3_node: False
[0m22:34:14.342522 [info ] [MainThread]:   connect_timeout: None
[0m22:34:14.342630 [info ] [MainThread]:   role: None
[0m22:34:14.342739 [info ] [MainThread]:   retries: 1
[0m22:34:14.342848 [info ] [MainThread]:   autocommit: True
[0m22:34:14.342959 [info ] [MainThread]:   access_key_id: None
[0m22:34:14.343293 [info ] [MainThread]: Registered adapter: redshift=1.9.0
[0m22:34:14.396636 [debug] [MainThread]: Acquiring new redshift connection 'debug'
[0m22:34:14.399561 [debug] [MainThread]: Using redshift connection "debug"
[0m22:34:14.399738 [debug] [MainThread]: On debug: select 1 as id
[0m22:34:14.399855 [debug] [MainThread]: Opening a new connection, currently in state init
[0m22:34:14.399993 [debug] [MainThread]: Redshift adapter: Connecting to Redshift with 'database' credentials method
[0m22:34:14.401924 [debug] [MainThread]: Redshift adapter: Establishing connection using ssl with `sslmode` set to 'prefer'.To connect without ssl, set `sslmode` to 'disable'.
[0m22:35:09.954674 [error] [MainThread]: Encountered an error:

[0m22:35:09.956798 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/dbt/cli/main.py", line 414, in debug
    results = task.run()
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/dbt/task/debug.py", line 144, in run
    connection_status = self.test_connection()
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/dbt/task/debug.py", line 465, in test_connection
    connection_result = self.attempt_connection(self.profile)
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/dbt/task/debug.py", line 443, in attempt_connection
    adapter.debug_query()
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/dbt/adapters/redshift/impl.py", line 190, in debug_query
    self.execute("select 1 as id")
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/dbt/adapters/base/impl.py", line 398, in execute
    return self.connections.execute(sql=sql, auto_begin=auto_begin, fetch=fetch, limit=limit)
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/dbt/adapters/redshift/connections.py", line 471, in execute
    _, cursor = self.add_query(sql, auto_begin)
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/dbt/adapters/redshift/connections.py", line 499, in add_query
    connection, cursor = super().add_query(
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/dbt/adapters/sql/connections.py", line 92, in add_query
    cursor = connection.handle.cursor()
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/dbt/adapters/contracts/connection.py", line 96, in handle
    self._handle.resolve(self)
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/dbt/adapters/contracts/connection.py", line 120, in resolve
    return self.opener(connection)
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/dbt/adapters/redshift/connections.py", line 452, in open
    open_connection = cls.retry_connection(
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/dbt/adapters/base/connections.py", line 237, in retry_connection
    connection.handle = connect()
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/dbt/adapters/redshift/connections.py", line 348, in connect
    c = redshift_connector.connect(**kwargs)
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/redshift_connector/__init__.py", line 394, in connect
    return Connection(
  File "/Users/lorenagongang/Documents/projects/datawarehouse_project/env/lib/python3.10/site-packages/redshift_connector/core.py", line 634, in __init__
    self._usock.connect(hostport)
KeyboardInterrupt

[0m22:35:09.961805 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 55.77848, "process_in_blocks": "0", "process_kernel_time": 0.130366, "process_mem_max_rss": "107839488", "process_out_blocks": "0", "process_user_time": 0.589562}
[0m22:35:09.963002 [debug] [MainThread]: Command `dbt debug` failed at 22:35:09.962832 after 55.78 seconds
[0m22:35:09.963549 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m22:35:09.964044 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1070b3d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118ae15a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118ae0bb0>]}
[0m22:35:09.964683 [debug] [MainThread]: Flushing usage events
[0m22:35:10.358597 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:35:18.867879 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103b17d00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1049e7460>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1049e6da0>]}


============================== 22:35:18.869648 | 0a7752bb-2b03-49e6-adbf-2759040bcc1a ==============================
[0m22:35:18.869648 [info ] [MainThread]: Running with dbt=1.9.0
[0m22:35:18.869912 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/lorenagongang/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m22:35:18.870145 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/lorenagongang/Documents/projects/datawarehouse_project/Infra/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:35:18.870717 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.033595834, "process_in_blocks": "0", "process_kernel_time": 0.056258, "process_mem_max_rss": "93585408", "process_out_blocks": "0", "process_user_time": 0.492063}
[0m22:35:18.870964 [debug] [MainThread]: Command `dbt run` failed at 22:35:18.870925 after 0.03 seconds
[0m22:35:18.871113 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103b17d00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1049e7ca0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1049e7190>]}
[0m22:35:18.871249 [debug] [MainThread]: Flushing usage events
[0m22:35:19.232577 [debug] [MainThread]: An error was encountered while trying to flush usage events
